// <auto-generated>
//     Generated by protoc-gen-cslink v1.0.0.  DO NOT EDIT!
//     source: nested_example.proto
// </auto-generated>

namespace Examples
{
    partial class TopMessage : Examples.INetMessage
    {
        public const ushort MsgId = 100;
        ushort Examples.INetMessage.MsgId { get { return MsgId; } }

        public const string MsgName = "TopMessage";
        string Examples.INetMessage.MsgName { get { return MsgName; } }
    }
    partial class TopMessage
    {
        partial class Types
        {
            partial class NestedMessage : Examples.INetMessage
            {
                public const ushort MsgId = 101;
                ushort Examples.INetMessage.MsgId { get { return MsgId; } }

                public const string MsgName = "NestedMessage";
                string Examples.INetMessage.MsgName { get { return MsgName; } }
            }
        }
    }
    partial class TopMessage
    {
        partial class Types
        {
            partial class ExcludedNestedMessage
            {
                partial class Types
                {
                    partial class NestedNestedMessage : Examples.INetMessage
                    {
                        public const ushort MsgId = 400;
                        ushort Examples.INetMessage.MsgId { get { return MsgId; } }

                        public const string MsgName = "NestedNestedMessage";
                        string Examples.INetMessage.MsgName { get { return MsgName; } }
                    }
                }
            }
        }
    }
}
