// <auto-generated>
//     Generated by protoc-gen-cslink v1.0.0.  DO NOT EDIT!
//     source: simple_example.proto
// </auto-generated>

namespace Examples
{
    partial class MessageA : Examples.INetMessage
    {
        public const ushort MsgId = 102;
        ushort Examples.INetMessage.MsgId { get { return MsgId; } }

        public const string MsgName = "MessageA";
        string Examples.INetMessage.MsgName { get { return MsgName; } }
    }
    partial class MessageB : Examples.INetMessage
    {
        public const ushort MsgId = 103;
        ushort Examples.INetMessage.MsgId { get { return MsgId; } }

        public const string MsgName = "MessageB";
        string Examples.INetMessage.MsgName { get { return MsgName; } }
    }
    partial class MessageC : Examples.INetMessage
    {
        public const ushort MsgId = 401;
        ushort Examples.INetMessage.MsgId { get { return MsgId; } }

        public const string MsgName = "MessageC";
        string Examples.INetMessage.MsgName { get { return MsgName; } }
    }
    partial class MessageD : Examples.INetMessage
    {
        public const ushort MsgId = 402;
        ushort Examples.INetMessage.MsgId { get { return MsgId; } }

        public const string MsgName = "MessageD";
        string Examples.INetMessage.MsgName { get { return MsgName; } }
    }
}
