// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.27.0--dev
// source: nested_example.proto

package examples

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @group="group/one"
type TopMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *TopMessage) Reset() {
	*x = TopMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nested_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopMessage) ProtoMessage() {}

func (x *TopMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nested_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopMessage.ProtoReflect.Descriptor instead.
func (*TopMessage) Descriptor() ([]byte, []int) {
	return file_nested_example_proto_rawDescGZIP(), []int{0}
}

func (x *TopMessage) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

// @group="group/one"
type TopMessage_NestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *TopMessage_NestedMessage) Reset() {
	*x = TopMessage_NestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nested_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopMessage_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopMessage_NestedMessage) ProtoMessage() {}

func (x *TopMessage_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nested_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopMessage_NestedMessage.ProtoReflect.Descriptor instead.
func (*TopMessage_NestedMessage) Descriptor() ([]byte, []int) {
	return file_nested_example_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TopMessage_NestedMessage) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

type TopMessage_ExcludedNestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *TopMessage_ExcludedNestedMessage) Reset() {
	*x = TopMessage_ExcludedNestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nested_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopMessage_ExcludedNestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopMessage_ExcludedNestedMessage) ProtoMessage() {}

func (x *TopMessage_ExcludedNestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nested_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopMessage_ExcludedNestedMessage.ProtoReflect.Descriptor instead.
func (*TopMessage_ExcludedNestedMessage) Descriptor() ([]byte, []int) {
	return file_nested_example_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TopMessage_ExcludedNestedMessage) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

// @group="group/two"
type TopMessage_ExcludedNestedMessage_NestedNestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *TopMessage_ExcludedNestedMessage_NestedNestedMessage) Reset() {
	*x = TopMessage_ExcludedNestedMessage_NestedNestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nested_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopMessage_ExcludedNestedMessage_NestedNestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopMessage_ExcludedNestedMessage_NestedNestedMessage) ProtoMessage() {}

func (x *TopMessage_ExcludedNestedMessage_NestedNestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nested_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopMessage_ExcludedNestedMessage_NestedNestedMessage.ProtoReflect.Descriptor instead.
func (*TopMessage_ExcludedNestedMessage_NestedNestedMessage) Descriptor() ([]byte, []int) {
	return file_nested_example_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *TopMessage_ExcludedNestedMessage_NestedNestedMessage) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

var File_nested_example_proto protoreflect.FileDescriptor

var file_nested_example_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x54, 0x6f, 0x70, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x69, 0x1a, 0x1d, 0x0a, 0x0d, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x69, 0x1a, 0x4a, 0x0a, 0x15, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x4e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x69,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x1a, 0x23, 0x0a, 0x13, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x42, 0x36,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61,
	0x6c, 0x6f, 0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x72, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0xaa, 0x02, 0x08, 0x45, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nested_example_proto_rawDescOnce sync.Once
	file_nested_example_proto_rawDescData = file_nested_example_proto_rawDesc
)

func file_nested_example_proto_rawDescGZIP() []byte {
	file_nested_example_proto_rawDescOnce.Do(func() {
		file_nested_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_nested_example_proto_rawDescData)
	})
	return file_nested_example_proto_rawDescData
}

var file_nested_example_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nested_example_proto_goTypes = []interface{}{
	(*TopMessage)(nil),                                           // 0: TopMessage
	(*TopMessage_NestedMessage)(nil),                             // 1: TopMessage.NestedMessage
	(*TopMessage_ExcludedNestedMessage)(nil),                     // 2: TopMessage.ExcludedNestedMessage
	(*TopMessage_ExcludedNestedMessage_NestedNestedMessage)(nil), // 3: TopMessage.ExcludedNestedMessage.NestedNestedMessage
}
var file_nested_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nested_example_proto_init() }
func file_nested_example_proto_init() {
	if File_nested_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nested_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nested_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopMessage_NestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nested_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopMessage_ExcludedNestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nested_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopMessage_ExcludedNestedMessage_NestedNestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nested_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nested_example_proto_goTypes,
		DependencyIndexes: file_nested_example_proto_depIdxs,
		MessageInfos:      file_nested_example_proto_msgTypes,
	}.Build()
	File_nested_example_proto = out.File
	file_nested_example_proto_rawDesc = nil
	file_nested_example_proto_goTypes = nil
	file_nested_example_proto_depIdxs = nil
}
