// Code generated by protoc-gen-golink. DO NOT EDIT.
// versions:
// 	protoc-gen-golink v1.0.0
// 	protoc            v5.27.0
// source: nested_example.proto

package examples

const (
	TopMessage_MsgId   uint16 = 100
	TopMessage_MsgName string = "TopMessage"
)

func (*TopMessage) MsgId() uint16   { return TopMessage_MsgId }
func (*TopMessage) MsgName() string { return TopMessage_MsgName }

const (
	TopMessage_NestedMessage_MsgId   uint16 = 101
	TopMessage_NestedMessage_MsgName string = "TopMessage_NestedMessage"
)

func (*TopMessage_NestedMessage) MsgId() uint16   { return TopMessage_NestedMessage_MsgId }
func (*TopMessage_NestedMessage) MsgName() string { return TopMessage_NestedMessage_MsgName }

const (
	TopMessage_ExcludedNestedMessage_NestedNestedMessage_MsgId   uint16 = 400
	TopMessage_ExcludedNestedMessage_NestedNestedMessage_MsgName string = "TopMessage_ExcludedNestedMessage_NestedNestedMessage"
)

func (*TopMessage_ExcludedNestedMessage_NestedNestedMessage) MsgId() uint16 {
	return TopMessage_ExcludedNestedMessage_NestedNestedMessage_MsgId
}
func (*TopMessage_ExcludedNestedMessage_NestedNestedMessage) MsgName() string {
	return TopMessage_ExcludedNestedMessage_NestedNestedMessage_MsgName
}

func init() {
	registerNetMessage(func() NetMessage { return new(TopMessage) })
	registerNetMessage(func() NetMessage { return new(TopMessage_NestedMessage) })
	registerNetMessage(func() NetMessage { return new(TopMessage_ExcludedNestedMessage_NestedNestedMessage) })
}
