// Code generated by protoc-gen-golink. DO NOT EDIT.
// versions:
// 	protoc-gen-golink v1.0.0

package examples

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
)

const (
	MsgGroupMin_GroupOne = 100
	MsgGroupMax_GroupOne = 300
	MsgGroupMin_GroupTwo = 400
	MsgGroupMax_GroupTwo = 900
)

type NetMessage interface {
	proto.Message
	MsgId() uint16
	MsgName() string
}

type msgInfo struct {
	name    string
	factory func() NetMessage
}

var msgInfoMap = make(map[uint16]*msgInfo)

func registerNetMessage(factory func() NetMessage) {
	msg := factory()
	msgInfoMap[msg.MsgId()] = &msgInfo{
		name:    msg.MsgName(),
		factory: factory,
	}
}

func NewMsgById(msgId uint16) (NetMessage, error) {
	info, ok := msgInfoMap[msgId]
	if !ok {
		return nil, fmt.Errorf("unknown message id: %d", msgId)
	}
	return info.factory(), nil
}

func MsgName(msgId uint16) (string, error) {
	info, ok := msgInfoMap[msgId]
	if !ok {
		return "", fmt.Errorf("unknown message id: %d", msgId)
	}
	return info.name, nil
}
