// Code generated by protoc-gen-golink. DO NOT EDIT.
// versions:
// 	protoc-gen-golink v1.0.0
// 	protoc            v5.27.0
// source: simple_example.proto

package examples

const (
	MessageA_MsgId   uint16 = 102
	MessageA_MsgName string = "MessageA"
)

func (*MessageA) MsgId() uint16   { return MessageA_MsgId }
func (*MessageA) MsgName() string { return MessageA_MsgName }

const (
	MessageB_MsgId   uint16 = 103
	MessageB_MsgName string = "MessageB"
)

func (*MessageB) MsgId() uint16   { return MessageB_MsgId }
func (*MessageB) MsgName() string { return MessageB_MsgName }

const (
	MessageC_MsgId   uint16 = 401
	MessageC_MsgName string = "MessageC"
)

func (*MessageC) MsgId() uint16   { return MessageC_MsgId }
func (*MessageC) MsgName() string { return MessageC_MsgName }

const (
	MessageD_MsgId   uint16 = 402
	MessageD_MsgName string = "MessageD"
)

func (*MessageD) MsgId() uint16   { return MessageD_MsgId }
func (*MessageD) MsgName() string { return MessageD_MsgName }

func init() {
	registerNetMessage(func() NetMessage { return new(MessageA) })
	registerNetMessage(func() NetMessage { return new(MessageB) })
	registerNetMessage(func() NetMessage { return new(MessageC) })
	registerNetMessage(func() NetMessage { return new(MessageD) })
}
