// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.27.0--dev
// source: simple_example.proto

package examples

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @group="group/one"
type MessageA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *MessageA) Reset() {
	*x = MessageA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageA) ProtoMessage() {}

func (x *MessageA) ProtoReflect() protoreflect.Message {
	mi := &file_simple_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageA.ProtoReflect.Descriptor instead.
func (*MessageA) Descriptor() ([]byte, []int) {
	return file_simple_example_proto_rawDescGZIP(), []int{0}
}

func (x *MessageA) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

// @group="group/one"
type MessageB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *MessageB) Reset() {
	*x = MessageB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageB) ProtoMessage() {}

func (x *MessageB) ProtoReflect() protoreflect.Message {
	mi := &file_simple_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageB.ProtoReflect.Descriptor instead.
func (*MessageB) Descriptor() ([]byte, []int) {
	return file_simple_example_proto_rawDescGZIP(), []int{1}
}

func (x *MessageB) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

// @group="group/two"
type MessageC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *MessageC) Reset() {
	*x = MessageC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageC) ProtoMessage() {}

func (x *MessageC) ProtoReflect() protoreflect.Message {
	mi := &file_simple_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageC.ProtoReflect.Descriptor instead.
func (*MessageC) Descriptor() ([]byte, []int) {
	return file_simple_example_proto_rawDescGZIP(), []int{2}
}

func (x *MessageC) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

// @group="group/two"
type MessageD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *MessageD) Reset() {
	*x = MessageD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageD) ProtoMessage() {}

func (x *MessageD) ProtoReflect() protoreflect.Message {
	mi := &file_simple_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageD.ProtoReflect.Descriptor instead.
func (*MessageD) Descriptor() ([]byte, []int) {
	return file_simple_example_proto_rawDescGZIP(), []int{3}
}

func (x *MessageD) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

var File_simple_example_proto protoreflect.FileDescriptor

var file_simple_example_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69,
	0x22, 0x18, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x12, 0x0c, 0x0a, 0x01,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x22, 0x18, 0x0a, 0x08, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x69, 0x22, 0x18, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44,
	0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x42, 0x36,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61,
	0x6c, 0x6f, 0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x72, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0xaa, 0x02, 0x08, 0x45, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simple_example_proto_rawDescOnce sync.Once
	file_simple_example_proto_rawDescData = file_simple_example_proto_rawDesc
)

func file_simple_example_proto_rawDescGZIP() []byte {
	file_simple_example_proto_rawDescOnce.Do(func() {
		file_simple_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_simple_example_proto_rawDescData)
	})
	return file_simple_example_proto_rawDescData
}

var file_simple_example_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_simple_example_proto_goTypes = []interface{}{
	(*MessageA)(nil), // 0: MessageA
	(*MessageB)(nil), // 1: MessageB
	(*MessageC)(nil), // 2: MessageC
	(*MessageD)(nil), // 3: MessageD
}
var file_simple_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simple_example_proto_init() }
func file_simple_example_proto_init() {
	if File_simple_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simple_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simple_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simple_example_proto_goTypes,
		DependencyIndexes: file_simple_example_proto_depIdxs,
		MessageInfos:      file_simple_example_proto_msgTypes,
	}.Build()
	File_simple_example_proto = out.File
	file_simple_example_proto_rawDesc = nil
	file_simple_example_proto_goTypes = nil
	file_simple_example_proto_depIdxs = nil
}
